FROM clearlinux:latest

RUN swupd bundle-add \
    curl \
    git \
    c-basic \
    devpkg-openssl

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app
COPY . .

RUN cargo build --release

RUN cp target/release/xpm /usr/local/bin/xpm

CMD ["xpm", "--version"]
