FROM archlinux:latest

RUN pacman -Syu --noconfirm && pacman -S --noconfirm \
    base-devel \
    rust \
    git \
    openssl \
    pkg-config

WORKDIR /app
COPY . .

RUN cargo build --release

RUN cp target/release/xpm /usr/local/bin/xpm

CMD ["xpm", "--version"]
